openapi: 3.0.1
info:
  title: MessageStoreForward_API
  description: API Definition of MessageStoreForward_API
  version: 1.0.0
servers:
- url: http://localhost:8290/messagestore
paths:
  /:
    get:
      responses:
        default:
          description: Default response
