openapi: 3.0.1
info:
  title: DemoApi
  description: API Definition of DemoApi
  version: 1.0.0
servers:
- url: http://localhost:8290/demo
paths:
  /:
    post:
      responses:
        default:
          description: Default response
