openapi: 3.0.1
info:
  title: UserDetails_API
  description: API Definition of UserDetails_API
  version: 1.0.0
servers:
- url: http://localhost:8290/user
paths:
  /:
    get:
      responses:
        default:
          description: Default response
