openapi: 3.0.1
info:
  title: Script-API
  description: API Definition of Script-API
  version: 1.0.0
servers:
- url: http://localhost:8290/script
paths:
  /:
    post:
      responses:
        default:
          description: Default response
