openapi: 3.0.1
info:
  title: UserValidating_API
  description: API Definition of UserValidating_API
  version: 1.0.0
servers:
- url: http://localhost:8290/user
paths:
  /:
    get:
      responses:
        default:
          description: Default response
